from .award import Award as Award
from .block import Block as Block
from .degree import Degree as Degree
from .job import Job as Job
from .list_block import ListBlock as ListBlock
from .project import Project as Project
from .publication import Publication as Publication
from .school import School as School
from .section_header import SectionHeader as SectionHeader
from .two_column import TwoColumn as TwoColumn
